name: app
type: "php:5.5"
build:
    flavor: drupal
access:
    ssh: contributor
relationships:
    database: "mysql:mysql"
web:
    document_root: "/"
    passthru: "/index.php"
disk: 2048
mounts:
    "/public/sites/default/files": "shared:files/files"
    "/tmp": "shared:files/tmp"
    "/private": "shared:files/private"
# hooks:
    # We run deploy hook after your application has been deployed and started.
#    deploy: |
#      cd public
#      drush site-install -y campsite --account-pass=admin --site-name="Iron Camp"
#      drush fra -y
#      drush cc all
# test
crons:
    drupal:
        spec: "*/20 * * * *"
        cmd: "cd public ; drush core-cron"
