<?php

/**
 * Implements hook_menu().
 */
function eventbrite_menu() {
  return array(
    'admin/config/system/eventbrite' => array(
      'title' => 'Eventbrite',
      'description' => 'Setup Eventbrite integration',
      'page callback' => 'eventbrite_admin_config_form',
      'access arguments' => array('administer site configuration'),
      'file' => 'eventbrite.admin.inc',
    ),
    'api/v3/eventbrite/endpoint' => array(
      'page callback' => 'eventbrite_webhook_process',
      'access arguments' => array('access content'),
    ),
  );
}

function eventbrite_webhook_process() {
  $request_body = file_get_contents('php://input');
  watchdog('eventbrite', $request_body);
}