<?php

/**
 * Implements hook_menu().
 */
function eventbrite_menu() {
  return array(
    'admin/config/system/eventbrite' => array(
      'title' => 'Eventbrite',
      'description' => 'Setup Eventbrite integration',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('eventbrite_admin_config_form'),
      'access arguments' => array('administer site configuration'),
      'file' => 'eventbrite.admin.inc',
    ),
    'api/v3/eventbrite/endpoint' => array(
      'page callback' => 'eventbrite_webhook_process',
      'access arguments' => array('access content'),
    ),
  );
}

function eventbrite_webhook_process() {
  $webhook = json_decode(file_get_contents('php://input'), TRUE);
  if ($webhook['config']['action'] === 'order.placed') {
    $token = variable_get('eventbrite_oauth_token', '');
    if (empty($token)) {
      watchdog('eventbrite', 'You have to fill your token first.', array(), WATCHDOG_ERROR);
      return;
    }
    $request_url = $webhook['api_url'] . '?expand=attendees&token=' . $token;
    $order = json_decode(file_get_contents($request_url), TRUE);
    watchdog('eventbrite', print_r($order, TRUE));
    $attendees = $order['attendees'];
    foreach ($attendees as $attendee) {
      $email = $attendee['profile']['email'];
      if (user_load_by_mail($email) !== FALSE) {
        $account = drupal_anonymous_user();
        $account->mail = $email;
        $account->name = $email;
        $account = user_save($account);
        // Notify user about new account.
        _user_mail_notify('register_admin_created', $account);
        watchdog('eventbrite', 'User #@id has been created', array('@id' => $account->uid), WATCHDOG_INFO);
      }
      else {
        watchdog('eventbrite', 'User with email @email has been created', array('@email' => $email), WATCHDOG_INFO);
      }
    }
  }
}